-- ============================================================
--  DJIGUI — Création de la base de données (PostgreSQL / Supabase)
--  Conversion de backend/sql/01-creation.sql (MariaDB/MySQL, gardé
--  intact pour référence). Même schéma, même dix-sept tables, mêmes
--  contraintes : seule la syntaxe change.
--
--  RÈGLES DE CONVERSION APPLIQUÉES :
--   - id_* INT AUTO_INCREMENT PRIMARY KEY
--       → INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--     « BY DEFAULT », pas « ALWAYS » : ça autorise un INSERT à préciser
--     lui-même la valeur de l'id (utile pour un futur import de données
--     existantes). CONSÉQUENCE À NE PAS OUBLIER : après tout import qui
--     insère des id explicites dans une table, la séquence associée
--     retarde sur le MAX() réel tant qu'elle n'est pas resynchronisée.
--     Pour chaque table concernée par un tel import, lancer :
--       SELECT setval(
--         pg_get_serial_sequence('nom_table', 'id_colonne'),
--         (SELECT COALESCE(MAX(id_colonne), 1) FROM nom_table)
--       );
--     Sinon le prochain INSERT sans id explicite peut entrer en conflit
--     avec un id déjà présent.
--   - Backticks, ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4, COLLATE et
--     AUTO_INCREMENT=n retirés : propres à MySQL, sans équivalent
--     en PostgreSQL (l'encodage d'une base Supabase est déjà UTF-8).
--   - TINYINT(1) / BOOLEAN(0|1) → BOOLEAN avec DEFAULT TRUE/FALSE.
--   - TINYINT (rang, hors booléen) → SMALLINT, PostgreSQL n'a pas TINYINT.
--   - DATETIME / TIMESTAMP → TIMESTAMPTZ. DEFAULT CURRENT_TIMESTAMP
--     reste valable tel quel.
--   - ENUM(...) → colonne texte + contrainte CHECK (colonne IN (...)),
--     comme demandé (plus simple à maintenir qu'un type ENUM Postgres).
--   - CURDATE() → CURRENT_DATE.
--   - INDEX ... déclaré dans la table (syntaxe MySQL) → CREATE INDEX
--     séparé après la table, seule syntaxe possible en PostgreSQL.
--   - UNIQUE KEY nommée → CONSTRAINT ... UNIQUE (...), même nom conservé
--     (nécessaire pour les ON CONFLICT du lot pilote, à venir).
--   - Noms de colonnes déjà en minuscules dans l'original : rien à faire.
--
--  ON UPDATE CURRENT_TIMESTAMP : recherché dans tout 01-creation.sql,
--  AUCUNE occurrence trouvée (grep confirmé). Aucune colonne ne s'appelle
--  updated_at et aucune ne porte cette clause. Donc AUCUNE table ne reçoit
--  de trigger set_updated_at() dans cette conversion — il n'y a rien à
--  déclencher. Si ce besoin apparaît plus tard, la fonction se rajoutera
--  à ce moment-là, avec les triggers sur les tables concernées.
--
--  CREATE DATABASE / USE djigui : retirés. Un projet Supabase fournit déjà
--  une base (« postgres ») ; le schéma se crée directement dedans, dans
--  le schéma « public » par défaut. Rien à créer ni à sélectionner avant
--  ces instructions.
-- ============================================================

/* ---------- T4 : structures ---------- */
CREATE TABLE structure_sang (
  id_structure   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom            VARCHAR(150) NOT NULL,
  type           VARCHAR(20) NOT NULL
                   CONSTRAINT chk_structure_type CHECK (type IN ('crts','depot','banque_hopital')),
  ville          VARCHAR(100) NOT NULL,
  adresse        VARCHAR(200),
  telephone      VARCHAR(20),
  horaires       VARCHAR(120),
  date_creation  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

/* ---------- T3 : zones ---------- */
CREATE TABLE zone (
  id_zone       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom           VARCHAR(100) NOT NULL,
  ville         VARCHAR(100) NOT NULL,
  date_creation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_zone UNIQUE (nom, ville)
);

/* ---------- T1 : utilisateurs ---------- */
CREATE TABLE utilisateur (
  id_utilisateur            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identifiant               VARCHAR(120) NOT NULL UNIQUE,
  mot_de_passe               VARCHAR(255) NOT NULL,
  role                      VARCHAR(20) NOT NULL
                              CONSTRAINT chk_utilisateur_role CHECK (role IN ('donneur','gestionnaire','admin')),
  nom                       VARCHAR(80)  NULL,   -- correction 1
  prenom                    VARCHAR(80)  NULL,   -- correction 1
  fonction                  VARCHAR(120) NULL,   -- correction 2
  id_structure              INT NULL,
  statut                    VARCHAR(20) NOT NULL DEFAULT 'actif'
                              CONSTRAINT chk_utilisateur_statut CHECK (statut IN ('actif','suspendu','desactive')),
  doit_changer_mot_de_passe BOOLEAN  NOT NULL DEFAULT FALSE,
  provisoire_expire_le      TIMESTAMPTZ NULL,       -- correction 3
  provisoire_deja_affiche   BOOLEAN  NOT NULL DEFAULT FALSE,
  nb_echecs_connexion       INT      NOT NULL DEFAULT 0,
  verrouille_jusqu_a        TIMESTAMPTZ NULL,
  derniere_connexion        TIMESTAMPTZ NULL,
  date_creation             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_utilisateur_structure FOREIGN KEY (id_structure)
    REFERENCES structure_sang(id_structure)
);

/* ---------- T2 : donneurs ---------- */
CREATE TABLE donneur (
  id_donneur                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_utilisateur             INT NOT NULL UNIQUE,
  nom                        VARCHAR(80) NOT NULL,
  prenom                     VARCHAR(80) NOT NULL,
  sexe                       VARCHAR(1) NOT NULL
                               CONSTRAINT chk_donneur_sexe CHECK (sexe IN ('M','F')),
  date_naissance             DATE NOT NULL,
  groupe_sanguin             VARCHAR(3) NULL -- correction 5 : NULL autorisé, « Je ne sais pas » (E4)
                               CONSTRAINT chk_donneur_groupe CHECK (
                                 groupe_sanguin IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  poids_declare              DECIMAL(5,2) NULL,      -- correctif 4 : non obligatoire, comme le groupe
  id_zone                    INT NOT NULL,
  repere_position            VARCHAR(200) NULL,
  question_securite          VARCHAR(200) NOT NULL,
  reponse_securite           VARCHAR(255) NOT NULL,
  accepte_sms                BOOLEAN NOT NULL DEFAULT TRUE,
  accepte_messagerie         BOOLEAN NOT NULL DEFAULT FALSE,
  date_dernier_don           DATE NULL,
  date_prochaine_eligibilite DATE NULL,
  statut                     VARCHAR(20) NOT NULL DEFAULT 'actif'
                               CONSTRAINT chk_donneur_statut CHECK (statut IN ('actif','suspendu','desactive')),
  date_consentement          TIMESTAMPTZ NOT NULL,
  date_creation              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_donneur_utilisateur FOREIGN KEY (id_utilisateur)
    REFERENCES utilisateur(id_utilisateur),
  CONSTRAINT fk_donneur_zone FOREIGN KEY (id_zone)
    REFERENCES zone(id_zone)
);
CREATE INDEX idx_ciblage ON donneur (statut, groupe_sanguin, id_zone);

/* ---------- T15 : téléphones du donneur ---------- */
CREATE TABLE telephone_donneur (
  id_telephone          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_donneur            INT NOT NULL,
  numero                VARCHAR(20) NOT NULL UNIQUE,
  rang                  SMALLINT NOT NULL,
  statut_joignabilite   VARCHAR(20) NOT NULL DEFAULT 'non_verifie'
                          CONSTRAINT chk_tel_statut CHECK (
                            statut_joignabilite IN ('non_verifie','confirme','injoignable')),
  date_dernier_controle DATE NULL,
  CONSTRAINT uk_rang UNIQUE (id_donneur, rang),
  CONSTRAINT chk_rang CHECK (rang BETWEEN 1 AND 4),
  CONSTRAINT fk_tel_donneur FOREIGN KEY (id_donneur)
    REFERENCES donneur(id_donneur)
);

/* ---------- T16 : tentatives de récupération ---------- */
CREATE TABLE tentative_recuperation (
  id_tentative   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  identifiant    VARCHAR(120) NOT NULL,
  date_tentative TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  succes         BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_tentative ON tentative_recuperation (identifiant, date_tentative);

/* ---------- T5 : seuils par structure et par groupe ---------- */
CREATE TABLE seuil_stock (
  id_seuil       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_structure   INT NOT NULL,
  groupe_sanguin VARCHAR(3) NOT NULL
                   CONSTRAINT chk_seuil_groupe CHECK (
                     groupe_sanguin IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  seuil_bas      INT NOT NULL DEFAULT 10,
  seuil_critique INT NOT NULL DEFAULT 5,
  modifie_par    INT NULL,
  date_modification TIMESTAMPTZ NULL,
  CONSTRAINT uk_seuil UNIQUE (id_structure, groupe_sanguin),
  CONSTRAINT chk_seuils CHECK (seuil_critique <= seuil_bas),
  CONSTRAINT fk_seuil_structure FOREIGN KEY (id_structure)
    REFERENCES structure_sang(id_structure),
  CONSTRAINT fk_seuil_agent FOREIGN KEY (modifie_par)
    REFERENCES utilisateur(id_utilisateur)
);

/* ---------- T9 : appels au don ---------- */
CREATE TABLE alerte (
  id_alerte        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_structure     INT NOT NULL,
  cree_par         INT NOT NULL,
  groupe_cible     VARCHAR(60) NULL,             -- correctif 3 : NULL si mode_ciblage <> 'groupe'
  mode_ciblage     VARCHAR(20) NOT NULL DEFAULT 'groupe'
                     CONSTRAINT chk_alerte_mode_ciblage CHECK (mode_ciblage IN ('groupe','zone','tous')),
  elargi_compatibles BOOLEAN NOT NULL DEFAULT FALSE,
  message          TEXT NOT NULL,
  canaux           VARCHAR(60) NOT NULL DEFAULT 'application',
  date_creation    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_envoi       TIMESTAMPTZ NULL,
  date_limite      DATE NULL,
  heure_limite     TIME NULL,                    -- correction 8
  statut           VARCHAR(20) NOT NULL DEFAULT 'brouillon'
                     CONSTRAINT chk_alerte_statut CHECK (statut IN ('brouillon','envoyee','cloturee')),
  nb_destinataires INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_alerte_structure FOREIGN KEY (id_structure)
    REFERENCES structure_sang(id_structure),
  CONSTRAINT fk_alerte_auteur FOREIGN KEY (cree_par)
    REFERENCES utilisateur(id_utilisateur)
);

/* Zones visées par un appel. L'annexe B n'en prévoyait qu'une seule ;
   E18 en fait cocher plusieurs. */
CREATE TABLE alerte_zone (
  id_alerte INT NOT NULL,
  id_zone   INT NOT NULL,
  PRIMARY KEY (id_alerte, id_zone),
  CONSTRAINT fk_az_alerte FOREIGN KEY (id_alerte) REFERENCES alerte(id_alerte),
  CONSTRAINT fk_az_zone   FOREIGN KEY (id_zone)   REFERENCES zone(id_zone)
);

/* ---------- T10 : destinataires figés à l'envoi ---------- */
CREATE TABLE alerte_destinataire (
  id_destinataire INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_alerte       INT NOT NULL,
  id_donneur      INT NOT NULL,
  canal_envoi     VARCHAR(20) NOT NULL
                    CONSTRAINT chk_dest_canal CHECK (canal_envoi IN ('application','sms','appel')),
  date_envoi      TIMESTAMPTZ NULL,
  statut_envoi    VARCHAR(20) NOT NULL DEFAULT 'en_attente'
                    CONSTRAINT chk_dest_statut CHECK (statut_envoi IN ('en_attente','envoye','echec')),
  CONSTRAINT uk_dest UNIQUE (id_alerte, id_donneur, canal_envoi),
  CONSTRAINT fk_dest_alerte  FOREIGN KEY (id_alerte)  REFERENCES alerte(id_alerte),
  CONSTRAINT fk_dest_donneur FOREIGN KEY (id_donneur) REFERENCES donneur(id_donneur)
);

/* ---------- T11 : réponses des donneurs ---------- */
CREATE TABLE reponse_alerte (
  id_reponse   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_alerte    INT NOT NULL,
  id_donneur   INT NOT NULL,
  reponse      VARCHAR(20) NOT NULL
                 CONSTRAINT chk_reponse_valeur CHECK (reponse IN ('je_viens','je_ne_peux_pas')),
  motif_refus  VARCHAR(30) NULL  -- correction 6
                 CONSTRAINT chk_reponse_motif CHECK (
                   motif_refus IN ('don_trop_recent','absent_de_la_ville','raison_de_sante','autre')),
  date_reponse TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  presente     BOOLEAN NULL,
  CONSTRAINT uk_reponse UNIQUE (id_alerte, id_donneur),
  CONSTRAINT fk_rep_alerte  FOREIGN KEY (id_alerte)  REFERENCES alerte(id_alerte),
  CONSTRAINT fk_rep_donneur FOREIGN KEY (id_donneur) REFERENCES donneur(id_donneur)
);

/* ---------- T12 : fiche de disponibilité ---------- */
CREATE TABLE fiche_disponibilite (
  id_fiche              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_reponse            INT NOT NULL UNIQUE,
  repere_position       VARCHAR(200) NOT NULL,
  moyen_deplacement     VARCHAR(30) NOT NULL
                          CONSTRAINT chk_fiche_moyen CHECK (moyen_deplacement IN (
                            'a_pied','deux_roues','voiture','transport_commun','aucun')),
  besoin_aide_transport BOOLEAN NOT NULL DEFAULT FALSE,
  aide_satisfaite       BOOLEAN NULL,
  creneau_prefere       VARCHAR(60),
  commentaire           VARCHAR(255),
  CONSTRAINT fk_fiche_reponse FOREIGN KEY (id_reponse)
    REFERENCES reponse_alerte(id_reponse)
);

/* ---------- T6 : dons ---------- */
CREATE TABLE don (
  id_don         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_donneur     INT NOT NULL,
  id_structure   INT NOT NULL,
  id_alerte      INT NULL,
  date_don       DATE NOT NULL,
  heure_don      TIME NULL,
  enregistre_par INT NOT NULL,
  poste          VARCHAR(40) NULL,
  observation    VARCHAR(255),
  CONSTRAINT fk_don_donneur   FOREIGN KEY (id_donneur)     REFERENCES donneur(id_donneur),
  CONSTRAINT fk_don_structure FOREIGN KEY (id_structure)   REFERENCES structure_sang(id_structure),
  CONSTRAINT fk_don_alerte    FOREIGN KEY (id_alerte)      REFERENCES alerte(id_alerte),
  CONSTRAINT fk_don_agent     FOREIGN KEY (enregistre_par) REFERENCES utilisateur(id_utilisateur)
);
CREATE INDEX idx_don_donneur ON don (id_donneur, date_don);

/* ---------- T7 : poches ---------- */
CREATE TABLE poche (
  id_poche         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code_poche       VARCHAR(30) NOT NULL UNIQUE,
  id_don           INT NOT NULL UNIQUE,
  id_structure     INT NOT NULL,
  groupe_sanguin   VARCHAR(3) NOT NULL
                     CONSTRAINT chk_poche_groupe CHECK (
                       groupe_sanguin IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
  date_prelevement DATE NOT NULL,
  date_peremption  DATE NOT NULL,
  statut           VARCHAR(20) NOT NULL DEFAULT 'collectee'
                     CONSTRAINT chk_poche_statut CHECK (statut IN (
                       'collectee','qualifiee','disponible','reservee',
                       'transfusee','detruite','perimee')),
  destination      VARCHAR(120),
  motif_destruction VARCHAR(120),
  CONSTRAINT fk_poche_don       FOREIGN KEY (id_don)       REFERENCES don(id_don),
  CONSTRAINT fk_poche_structure FOREIGN KEY (id_structure) REFERENCES structure_sang(id_structure)
);
CREATE INDEX idx_stock ON poche (id_structure, groupe_sanguin, statut);

/* ---------- T8 : historique des poches ---------- */
CREATE TABLE poche_historique (
  id_historique   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_poche        INT NOT NULL,
  ancien_statut   VARCHAR(20),
  nouveau_statut  VARCHAR(20) NOT NULL,
  precision_etape VARCHAR(150),
  modifie_par     INT NOT NULL,
  poste           VARCHAR(40) NULL,              -- correction 7
  date_changement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_hist_poche FOREIGN KEY (id_poche)    REFERENCES poche(id_poche),
  CONSTRAINT fk_hist_agent FOREIGN KEY (modifie_par) REFERENCES utilisateur(id_utilisateur)
);
CREATE INDEX idx_hist ON poche_historique (id_poche, date_changement);

/* ---------- T13 : paramètres réglables ---------- */
CREATE TABLE parametre (
  cle          VARCHAR(60) PRIMARY KEY,
  valeur       VARCHAR(120) NOT NULL,
  libelle      VARCHAR(120) NOT NULL,
  consequence  VARCHAR(200) NOT NULL,
  unite        VARCHAR(20)  NOT NULL,
  categorie    VARCHAR(20) NOT NULL
                 CONSTRAINT chk_param_categorie CHECK (categorie IN ('medical','conservation','securite')),
  modifie_par  INT NULL,
  date_modification TIMESTAMPTZ NULL,
  CONSTRAINT fk_param_agent FOREIGN KEY (modifie_par)
    REFERENCES utilisateur(id_utilisateur)
);

/* ---------- T14 : journal d'activité ---------- */
CREATE TABLE journal_activite (
  id_journal     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_utilisateur INT NULL,
  action         VARCHAR(120) NOT NULL,
  cible          VARCHAR(200),
  resultat       VARCHAR(20) NOT NULL DEFAULT 'reussie' -- correction 4
                   CONSTRAINT chk_journal_resultat CHECK (resultat IN ('reussie','refusee','echouee')),
  date_action    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_journal_utilisateur FOREIGN KEY (id_utilisateur)
    REFERENCES utilisateur(id_utilisateur)
);
CREATE INDEX idx_journal ON journal_activite (date_action);
CREATE INDEX idx_journal_auteur ON journal_activite (id_utilisateur, date_action);
