-- ============================================================
--  DJIGUI — abonnements Web Push (PostgreSQL / Supabase).
--  Nouvelle table isolée : aucune table existante n'est modifiée.
--  À importer une fois, après 01-creation.postgresql.sql (référence
--  donneur.id_donneur).
--
--  Le push est un canal EN PLUS du canal « application », jamais une
--  dépendance : cette table peut rester vide sans que rien d'autre ne
--  casse. Pas de colonne « actif » — un abonnement mort se détecte à
--  l'envoi (le service de push répond 410 Gone) et la ligne se
--  supprime à ce moment-là plutôt que d'ajouter un état à maintenir.
-- ============================================================

CREATE TABLE abonnement_push (
  id_abonnement      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_donneur         INT NOT NULL,
  endpoint           TEXT NOT NULL,
  cle_p256dh         VARCHAR(255) NOT NULL,
  cle_auth           VARCHAR(255) NOT NULL,
  date_creation      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_dernier_envoi TIMESTAMPTZ NULL,
  CONSTRAINT uk_abonnement_endpoint UNIQUE (endpoint),
  CONSTRAINT fk_abonnement_donneur FOREIGN KEY (id_donneur)
    REFERENCES donneur(id_donneur)
);
CREATE INDEX idx_abonnement_donneur ON abonnement_push (id_donneur);
